/* General Action Types */
export const SET_FIRST_LAUNCH = "SET_FIRST_LAUNCH";
export const SET_LOADING = "SET_LOADING";
export const SET_TOAST = "SET_TOAST";

/* Auth Action Types */
export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const LOADING = "LOADING";
export const SEND_OTP_ERROR = "SEND_OTP_ERROR";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const SAVE_ZEGO_TOKEN = "SAVE_ZEGO_TOKEN";
export const SAVE_ID = "SAVE_ID";
export const SAVE_AVATAR = "SAVE_AVATAR";
export const SET_EDUCATION_DETAILS = "SET_EDUCATION_DETAILS";
export const SET_EXPERIENCE_DETAILS = "SET_EXPERIENCE_DETAILS";
export const SET_EXPERT_DETAILS = "SET_EXPERT_DETAILS";
export const SET_RATE_DETAILS = "SET_RATE_DETAILS";
export const SAVE_GOVID = "SAVE_GOVID";
export const COMPLETE_REGISTRATION = "COMPLETE_REGISTRATION";
export const LOGGED_IN = "LOGGED_IN";
export const LOGOUT = "LOGOUT";

/* Job Category */
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_DISTANCE = "SET_DISTANCE";
export const SET_ALL_CATEGORIES = "SET_ALL_CATEGORIES";
export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_DISTANCE_JOBS = "GET_DISTANCE_JOBS";

/* Interface Action Types */
export const CATEGORY_MODAL_ACTIVE = "CATEGORY_MODAL_ACTIVE";
export const MILESTONE_MODAL_ACTIVE = "MILESTONE_MODAL_ACTIVE";
export const PRIVACY_MODAL_ACTIVE = "PRIVACY_MODAL_ACTIVE";
export const TERMS_MODAL_ACTIVE = "TERMS_MODAL_ACTIVE";

// Projects Action Types
export const INITIATE_NEW_PROJECT = "INITIATE_NEW_PROPJECT";
export const PROJECT_MODAL_ACTIVE = "PROJECT_MODAL_ACTIVE";
export const SAVE_PROJECT_OVERVIEW = "SAVE_PROJECT_OVERVIEW";
export const SAVE_PROJECT_DETAILS = "SAVE_PROJECT_DETAILS";
export const SET_PROJECT_TITLE = "SET_PROJECT_TITLE";
export const SET_PROJECT_RESPONSE = "SET_PROJECT_RESPONSE";
export const SET_SHOW_TOAST = "SET_SHOW_TOAST";
export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const GET_PROJECTS = "GET_PROJECTS";

//experimental
export const SAVE_PROJECT = "SAVE_PROJECT";

// Chat
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";

// Location
export const SET_LOCATION = "SET_LOCATION";

// Wallet
export const SAVE_BALANCE = "SAVE_BALANCE";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SET_ALL_TRANSACTIONS = "SET_ALL_TRANSACTIONS";
